name: Update publication info

on:
  workflow_dispatch:
  schedule:
  - cron: '0 6 * * 1-5'

jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Setup Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - run: pip install requests scholarly
    - uses: actions/checkout@v3
    - name: Execute the script
      env:
        ADS_DEV_KEY: ${{ secrets.ADS_TOKEN }}
      run: python build_pub.py $ADS_DEV_KEY
    - name: commit changes
      run: |
        git config user.name SebastianBocquet
        git config user.email sebastian.bocquet@gmail.com
        git add pub.html
        git commit -m "Auto-update publication page"
        git push origin main
