name: Update publication info

on:
  schedule:
  - cron: '0 0 * * *'

jobs:
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.7 

    - name: Install Requirements
      run: pip install -r requirements.txt

    - name: Execute the script
      env:
        ADS_DEV_KEY: ${{ secrets.ADS_TOKEN }}
      run: python build_pub.py $ADS_DEV_KEY
    
    - name: commit changes
      run:
        git config user.name SebastianBocquet
        git config user.email sebastian.bocquet@gmail.com
        chmod +x ./scripts/commit.sh
        ./scripts/commit.sh
